### ISSUE TITLE
Add eslint configuration to ALE linters

### ISSUE THREAD

**Issue by jpesce** [kevinoid/vim-jsonc#13]
Eslint allows linting via the [eslint-plugin-jsonc plugin](https://ota-meshi.github.io/eslint-plugin-jsonc/).

I've tested it with ALE and it works fine, we just need to add the following linter configuration:
https://github.com/jpesce/vim-jsonc/blob/master/ale_linters/jsonc/eslint.vim
```vim
call ale#linter#Define('jsonc', {
\   'name': 'eslint',
\   'output_stream': 'both',
\   'executable': function('ale#handlers#eslint#GetExecutable'),
\   'cwd': function('ale#handlers#eslint#GetCwd'),
\   'command': function('ale#handlers#eslint#GetCommand'),
\   'callback': 'ale#handlers#eslint#HandleJSON',
\})
```

To make it easier, if you want I can make the pull request.

**Comment by kevinoid** [comment]
Neat!  Good find @jpesce!

Have you considered submitting a PR to https://github.com/dense-analysis/ale so all ALE users could benefit, whether or not they use this particular jsonc plugin?  If there's reason not to, I'm not opposed to adding it here.  Just trying to find the best spot.

**Comment by jpesce** [comment]
@kevinoid great! 🐸 I just made the pull request:
https://github.com/dense-analysis/ale/pull/3873

Let's see what they think

**Comment by kevinoid** [comment]
Great work!  Thanks again @jpesce!

I'll follow that PR and issue.  Let me know if there's anything I can do to help.

**Comment by kevinoid** [comment]
Congratulations on getting dense-analysis/ale#3873 merged, and thanks for all of your effort on it @jpesce!

Presumably there's no longer a benefit to adding the configuration to this plugin, so I'll close this issue.  Feel free to reopen if there's anything I've missed.
